services:
  app:
    build:
      context: ./sources/app
    container_name: tp3_app
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app_net

  db:
    image: mysql:8.0
    container_name: tp3_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sources/db/articles.sql:/docker-entrypoint-initdb.d/articles.sql:ro
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  db_data:
