services:
  app:
    build:
      context: ./sources/app
    container_name: tp3_app
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_net

  db:
    build:
      context: ./sources/db
    container_name: tp3_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 30s
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  db_data:
